### ISSUE TITLE
Add any 2 medium level Questions from Codechef  

### ISSUE THREAD

**Issue by kamleshjoshi8102** [kamleshjoshi8102/Codechef_practice#1]

**Comment by Jaishree-19** [comment]
I would like to contribute to this repo, please assign me a tag as a hactoberfest contributor

**Comment by kamleshjoshi8102** [comment]
go ahead @Jaishree-19

**Comment by phileinsophos** [comment]
PR raised

**Comment by Prince-ranjan** [comment]
I would like to contribute to this repo, please assign me a tag as a hactoberfest contributor.
