### ISSUE TITLE
Adding Codechef October Long challenge

### ISSUE THREAD

**Issue by Akshat293** [kamleshjoshi8102/Codechef_practice#4]
@kamleshjoshi8102 
 I want to add the recent codechef long challenge solutions.

**Comment by kamleshjoshi8102** [comment]
>  @kamleshjoshi8102 
>  I want to add the recent codechef long challenge solutions.

Go ahead @tom635 : ) but not of October that challenge is still going it'll be counted as cheating 🙂

**Comment by Akshat293** [comment]
> > @kamleshjoshi8102
> > I want to add the recent codechef long challenge solutions.
> 
> Go ahead @tom635 : ) but not of October that challenge is still going it'll be counted as cheating 🙂

ok sir
